config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'parks#index'
    get '/parks' => 'parks#index', as: 'parks'
    get '/parks/new' => 'parks#new', as: 'new_park'
    post '/parks' => 'parks#create'
    get '/parks/:id' => 'parks#show' , as: 'park'
    get '/parks/:id/edit' => 'parks#edit', as: 'edit_park'
    patch '/parks/:id' => 'parks#update'
    delete '/parks/:id' => 'parks#destroy'

    get '/rangers' => 'rangers#index', as: 'rangers'
    get '/rangers/new' => 'rangers#new', as: 'new_ranger'
    post '/rangers' => 'rangers#create'
    get '/rangers/:id' => 'rangers#show' , as: 'ranger'
    get '/rangers/:id/edit' => 'rangers#edit', as: 'edit_ranger'
    patch '/rangers/:id' => 'rangers#update'
    delete '/rangers/:id' => 'rangers#destroy'


    get '/parks/:park_id/rangers' => 'rangers#index', as: 'park_rangers'
    get '/parks/:park_id/rangers/new' => 'rangers#create', as: 'new_park_ranger'
    post '/parks/:park_id/rangers' => 'rangers#create'

    get '/rangers/:ranger_id/parks' => 'parks#index', as: 'ranger_parks'
    get '/rangers/:ranger_id/parks/new' => 'parks#create', as: 'new_ranger_parks'
    post '/rangers/:ranger_id/parks' => 'parks#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ActiveRecord::Base
  has_and_belongs_to_many :rangers
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }

end

app/models/ranger.rb
class Ranger < ActiveRecord::Base
  has_and_belongs_to_many :parks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController

  def index

  end

  def new
    @rangers = Ranger.all
    # so that later we can select the rangers we want to include in the park
  end

  def create
    @park = Park.new(park_params)

    @park.save
    redirect_to @park
  end

  def show
    @park = Park.find(params[:id])
    @ranger = @park.rangers.all    #where(park_id: params[:park_id])
  end

private

  def park_params
    params.require(:park).permit(:name, :description, :ranger_ids => [])
  end

  def ranger_params
    params.require(:ranger).permit(:name, :park_ids => [])
  end

end

app/controllers/rangers_controller.rb
class RangersController < ApplicationController

  def index

  end

  def new
    @parks = Park.all
    # so that later we can select the park that we want to add rangers to...
  end

  def create
    @ranger = Ranger.new(ranger_params)

    @ranger.save
    redirect_to @ranger
  end

  def show
    # deal with the case that we are trying to get a ranger for a park that doesn't exist
    @ranger = Ranger.find(params[:id])
    @park = @ranger.parks.all

    # if params[:park_id].to_i != @ranger.park.id
    #   # do something
    # end
  end

private

  def ranger_params
    params.require(:ranger).permit(:name, :park_id, :park_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/rangers_helper.rb
module RangersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parkng</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parks/index.html.erb
<h1>Hello World. This is parkng parks index view</h1>

app/views/parks/new.html.erb
<h3> Testing this header outside the .form-title class </h3>
<p class = 'form-title'> New Park form</p>
<p class = 'sub-title'> enter other stuff here </p>

<%= form_with scope: :park, url: parks_path, local: true do |form| %>

	<p>
		<%= form.collection_check_boxes :ranger_ids, @rangers, :id, :name %>
	</p>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/parks/show.html.erb
<p>
  <strong>Name of Park:</strong>
  <%= @park.name.capitalize %>
</p>

<p>
  <strong>Description:</strong>
  <%= @park.description %>
</p>

<p>
  <strong>Rangers in charge of this park:</strong>


 <% @ranger.each do |ranger| %>
    <tr>
      <td><%= ranger.name.capitalize %></td>
      <%# <td><%= link_to 'Show', edit_article_path(article)%>
    </tr>
  <% end %>
</p>

<%# <%= link_to 'Back', root_path %>
<%# <%= link_to 'Edit', edit_article_path(@article) %>

app/views/rangers/index.html.erb
<h1>Hello World. This is parkng index rangers view</h1>

<%= form.collection_check_boxes :ranger_ids, @rangers, :id, :name %>

app/views/rangers/new.html.erb
<%= form_with scope: :ranger, url: rangers_path, local: true do |form| %>

	<p>
  	<%= form.collection_select :park_id, @parks, :id, :name %>
	</p>

  <p>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/rangers/show.html.erb
<p>
  <strong>Ranger Name:</strong>
  <%= @ranger.name.capitalize %>
</p>

<p>
  <strong>Parks under this ranger's care:</strong>


 <% @park.each do |park| %>
    <tr>
      <td><%= park.name.capitalize %></td>
		</tr>
  <% end %>
  <%# <%= @article.text %>
</p>

<%= link_to 'Back', root_path %>
<%# <%= link_to 'Edit', edit_article_path(@article) %>